import os


AZURE_OPENAI_KEY = os.environ["AZURE_OPENAI_KEY"]
AZURE_OPENAI_LLM_ENDPOINT = os.environ["AZURE_OPENAI_LLM_ENDPOINT"]
AZURE_OPENAI_EMBEDDING_ENDPOINT = os.environ["AZURE_OPENAI_EMBEDDING_ENDPOINT"]
AZURE_OPENAI_VERSION = os.environ['AZURE_OPENAI_VERSION']